version: '3.7'

services:
    web:
        build: .
        command: python ./bot/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=trader
            - POSTGRES_PASSWORD=trading2077
            - POSTGRES_DB=trading_db

volumes:
    postgres_data:
