# Generated by Django 3.1.6 on 2021-05-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradinghistory',
            name='sell_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tradinghistory',
            name='total',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
