# Generated by Django 3.1.6 on 2021-05-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20210503_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinghistory',
            name='type_order',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=10),
            preserve_default=False,
        ),
    ]
